### ISSUE TITLE
Ed-Fi

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/edu-data-standards#1]
Hey All-

As discussed on the conference call, we are thinking about adopting [ed-fi](http://www.ed-fi.org/) as the data standard for our two projects. 

This is the thread to discuss the pros and cons, post research and knowledge,x and hopefully by the week of June 8th we can make a decision. 

As @almartin82 stated on the call, we're mostly at the soft yes stage, that is, use the standard until it makes our lives difficult.

**Comment by almartin82** [comment]
Agreed! Where soft yes is defined as "we'll use it until it gets in the
way, at which point we'll do our own thing." Hard yes would be that we
prioritize adhering to the standard as an end in it's own right (even if
that makes some features/tasks harder)

(mobile)

**Comment by hunterowens** [comment]
Ok. One bit of comment. EdFi has a [ODS](https://techdocs.ed-fi.org/display/ETKB/Ed-Fi+Operational+Data+Store+and+API) - short for operational data store, which is not open sourced yet- somewhat problematic for me, as a signal. 

Otherwise, another bit of a problem for us at KIPP/Impact Lab is that the schema has no integration that suggests anything about exposing data to students. [1]

The EdFi [Unified Data Model](https://techdocs.ed-fi.org/display/EFDS20/Unifying+Data+Model+-+Design+Principles) page is worth a read. The linked chart is basically a why is this problem such an difficult one to deal. 

For those looking for the technical guts, the [EdFi XML schema reference](https://techdocs.ed-fi.org/display/EFDS20/XML+Schema+-+Core+Schema+Overview) is that. 

I'm going to try and right a _toy_ implementation of some bit of EdFi tech today, so will let y'all know how that goes. 

[1] There is no way to express a permissions structure that includes students.

**Comment by hunterowens** [comment]
The DataStore and Data Store API are REST based, and only have code examples in Java and C#. No uri endpoints provided.

**Comment by hunterowens** [comment]
Bumping. I suspect, but need to confirm with @almartin82, that EdFi will not be part of the V1 version of our project.

**Comment by alexsoble** [comment]
Here are a few thoughts. I've been looking at the [PDF description of Version 1.2](http://www.ed-fi.org/assets/2013/11/Public-Ed-Fi-Logical-Database-Model-1.2.pdf). I found the [Version 2.0 site](https://techdocs.ed-fi.org/display/ETKB/Data+Standard+v2.0) super confusing and unclear.

**Assessments**:
- Overall makes sense (I like `AssessmentFamily` for capturing commonalities across assessments) but `AssessmentAssessmentFamily` is not a good look.
- The chart on page 10 is bananas.

**Discipline**:
- `DisciplineIncident` is described as "offense in violation of laws, rules, policies, or norms of behavior." No model for positive behavior. 
- Would prefer more holistic modeling of behavior as opposed to just discipline.

**Interventions**:
- `InterventionPrescription`: "Formal prescription of an instructional approach focusing on the specific techniques and materials used to teach a given subject. This can be prescribed by academic research, an interventions vendor, or other entity." 
  - What about classroom level interventions prescribed by teachers, i.e. assess and reteach for flexible groupings? This seems like a narrow concept of what intervention means.

Curious to hear more about what you are thinking @hunterowens @almartin82. Am I right in saying that if we don't go with Ed-Fi, we'll want to identify another standard that better fits our needs?

(cc @marimuraki)

**Comment by alexsoble** [comment]
Another thought. Might be interesting to talk about this with some of the companies doing SIS ETL. [Schoolzilla](https://schoolzilla.org/), [LearnSprout](http://www.learnsprout.com/), [BrightBytes](http://brightbytes.net/) are the ones on my radar. I'm sure all of them have put thought into data standards questions. Don't know if any of them are using a data standard, or if they're all doing their own thing. But could be a good source of insight, build out a wider community of practice.

**Comment by hunterowens** [comment]
Opening a new issue on reaching out about SIS ETL, closing EdFi because doesn't meet our needs, right now.

**Comment by almartin82** [comment]
per convo at KIPP data retreat, eScholar also has a data model used by big
state depertments of education

(mobile)

**Comment by hunterowens** [comment]
Will research.
