### ISSUE TITLE
Systems that we want to integrate with

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/edu-data-standards#2]
Let's list them, to start.

**Comment by marimuraki** [comment]
- PowerSchool
  - KIPP schools
- Aspen (X2) 
  - Somerville Public Schools @alexsoble @AmirHadjihabib 
- Aeries
- InfiniteCampus
- Skyward
- ...

Is there information readily available on what SIS are out there and how many districts / schools / students use each?

**Comment by almartin82** [comment]
This [article](https://medium.com/@prsmith2009/journey-into-the-center-of-the-world-of-student-information-systems-cea16d464597) has the best numbers I have seen. Powerschool, infinite campus, skyward, in
order of share.

Illuminate is growing like crazy. They're going to be up there soon

(mobile)
