### ISSUE TITLE
Schoolzilla and other SIS ETL companies

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/edu-data-standards#3]
Are they building a psudo-standard, as @chrishaid mentioned?

**Comment by almartin82** [comment]
Also, what is their view on edfi? Do they view a project like this as a
boon (generally reduces friction, adds a tool in the toolbox)?

(mobile)

**Comment by alexsoble** [comment]
Working on email outreach about this. Schoolzilla, BrightBytes, LearnSprout.

**Comment by chrishaid** [comment]
Schoolzilla just reached out to me on another topic and Andrew and I know a couple folks over there.  We can reach out if you want.

**Comment by alexsoble** [comment]
@chrishaid — Sure! Could you get one of their data people on our next group phone call so that we could talk data standards?

**Comment by hunterowens** [comment]
Happy to do an intro phone call to talk about what Alex and I have been
working on before the next group call, as well.

Thanks!

**Comment by alexsoble** [comment]
Hey team! Just reached out to my contacts at LearnSprout and BrightBytes (but not Schoolzilla) with emails introducing this question.  Here's what I said:

> Team Somerville here from Code for America! After doing more user research and market research with our partners, we are working on a [Student Insights tool](https://github.com/codeforamerica/somerville-teacher-tool) to help Somerville educators support students. 
> 
> We are curious about the idea of collaborating on data standards. 
> 
> Our tool starts with Somerville extracting data from its Aspen/X2 Student Information System via SQL scripts. The app we are building stands on top of this data. We are wondering: Does LearnSprout follow any particular data standard when it extracts info from school district Student Information Systems? If we aligned on data standards, might school districts like Somerville be able to more easily adopt different edtech products, and could those products be interoperable?
> 
> What do you think and who would be the right person at LearnSprout to talk with about these questions?
> 
> Thanks so much! 

Will let you know when I hear back!

**Comment by CodySF** [comment]
Awesome stuff! I'm looking forward to what they say.  
We should definitely play up what's in it for them: data standard = easier for other schools to use their product. 
Cody

**Comment by alexsoble** [comment]
:+1: :+1: 

@hunterowens, @almartin82 —@CodySF is a fantastic Code for SF brigade member who's working with us on this project.

**Comment by hunterowens** [comment]
@CodySF Welcome aboard! Looking forward to working with you.

**Comment by alexsoble** [comment]
Hey all,

Here's what we've heard back from [BrightBytes](http://brightbytes.net/):

> Hi Alex, Mari and Amir,
> 
> Here's the answer I got from our dev team. For context, since we're a research organization we don't endorse any particular company or approach. And since much of what we do is proprietary, we can't share much about our process. So here's dev's response: 
> 
> "This isn't an endorsement, nor is it a confirmation of technology used internally. It is, however, a few places to begin researching:
> 
> Common Education Data Standards (CEDS) https://ceds.ed.gov/Default.aspx
> School Interoperability Framework (SIF) https://www.sifassociation.org/Pages/default.aspx
> Ed-Fi Alliance http://www.ed-fi.org/
> 
> I hope this helps :) Please let me know if there's anything else I can help with.

**Comment by alexsoble** [comment]
Here are the [entities in the SIF specification](http://specification.sifassociation.org/Implementation/NA/3.3/html/indexFiles/EntityObjects.html).

**Comment by alexsoble** [comment]
Here is the [CEDS entity schema](https://ceds.ed.gov/domainEntitySchema.aspx).
