### ISSUE TITLE
SIS ETL

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/edu-data-standards#7]
Who is doing SIS ETL, and how. References #1. 

The Gates Foundation [Teachers Know Best Report](https://s3.amazonaws.com/edtech-production/reports/Gates-TeachersKnowBest-MakingDataWork.pdf) suggests that summit charter schools in the Bay Area has designed a full fledged teacher facing dashboard, which @alexsoble and CFA Somerville might want to dig in on. 

Futhermore, quoting @alexsoble here for the record. 

Another thought. Might be interesting to talk about this with some of the companies doing SIS ETL. Schoolzilla, LearnSprout, BrightBytes are the ones on my radar. I'm sure all of them have put thought into data standards questions. Don't know if any of them are using a data standard, or if they're all doing their own thing. But could be a good source of insight, build out a wider community of practice.

**Comment by almartin82** [comment]
I know Jon from summit -- good people! I can reach out

(mobile)

**Comment by hunterowens** [comment]
Might be worth normalizing the data to use the CEDS standard names.

**Comment by hunterowens** [comment]
Closing non-actionable.
